name: DeepSaffix Production Build

on:
  repository_dispatch:
    types: [frontend-updated]
  workflow_dispatch:

jobs:
  prepare-release:
    runs-on: ubuntu-latest # Solo necesitamos uno
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_TOKEN }} # CRUCIAL: Usar PAT para que el push dispare el siguiente workflow
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Download Frontend
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          workflow: main.yml
          run_id: ${{ github.event.client_payload.run_id }}
          name: frontend-dist
          repo: Grupo-2-DPM/DeepSaffix-WEB
          path: dist

      - name: Install Dependencies
        run: npm install

      - name: Set Version and Push Tag
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Evitar problemas de CRLF en Windows si hubiera archivos de texto
          git config core.autocrlf false

          git add dist/ -f 
          
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          NEW_VERSION="v${PACKAGE_VERSION}-build.${{ github.run_number }}"
          
          # npm version creará el commit con el 'dist' y el tag
          npm version $NEW_VERSION -m "Release $NEW_VERSION [skip ci]" --force
          
          git push origin main --follow-tags